### ISSUE TITLE
enable tag words for posts

### ISSUE THREAD

**Issue by MatthijsvanGils** [tilburgsciencehub/tilburg-ai#6]
__Background:__

We have developed a content strategy, distinguishing between #teachers and #students, knowledge levels (#starter, #intermediate, #pro), and content categories (#examples, #proscons, #howto). However, the current site doesn''t allow us to use any of these tag words, they will be useful though later for ordering posts.

__Deliverable:__

- A way to tag posts so that we can later use it for filtering.
- An explanation on how to do it.

**Comment by hannesdatta** [comment]
Oh, never mind. We found it.
